//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class elaborderdetail
    {
        public int eappointmentid { get; set; }
        public int labid { get; set; }
        public string labname { get; set; }
        public string labdescription { get; set; }
        public int eappointmentdetailid { get; set; }
    
        public virtual elabordermaster elabordermaster { get; set; }
        public virtual labmaster labmaster { get; set; }
    }
}
