//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientmaster
    {
        public patientmaster()
        {
            this.ebillordermasters = new HashSet<ebillordermaster>();
            this.elabordermasters = new HashSet<elabordermaster>();
        }
    
        public int patientid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string country { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<long> mobile { get; set; }
        public string emailid { get; set; }
        public int deleted { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual ICollection<ebillordermaster> ebillordermasters { get; set; }
        public virtual ICollection<elabordermaster> elabordermasters { get; set; }
        public virtual patientlookup patientlookup { get; set; }
    }
}
