//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebillordermaster
    {
        public ebillordermaster()
        {
            this.ebillorderdetails = new HashSet<ebillorderdetail>();
        }
    
        public int ebillid { get; set; }
        public int eappointmentid { get; set; }
        public int patientid { get; set; }
        public int empid { get; set; }
        public string source { get; set; }
        public Nullable<int> refdocid { get; set; }
        public System.DateTime billdate { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public decimal billamount { get; set; }
        public decimal rounded { get; set; }
        public decimal discount { get; set; }
        public decimal discamnt { get; set; }
        public decimal totalamnt { get; set; }
        public decimal settleamnt { get; set; }
        public decimal amntrendered { get; set; }
    
        public virtual ICollection<ebillorderdetail> ebillorderdetails { get; set; }
        public virtual elabordermaster elabordermaster { get; set; }
        public virtual employeemaster employeemaster { get; set; }
        public virtual patientmaster patientmaster { get; set; }
    }
}
