//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class elabordermaster
    {
        public elabordermaster()
        {
            this.ebillordermasters = new HashSet<ebillordermaster>();
            this.elaborderdetails = new HashSet<elaborderdetail>();
        }
    
        public int eappointmentid { get; set; }
        public int patientid { get; set; }
        public int empid { get; set; }
        public System.DateTime appointmentdate { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int deleted { get; set; }
        public int refdocid { get; set; }
    
        public virtual ICollection<ebillordermaster> ebillordermasters { get; set; }
        public virtual ICollection<elaborderdetail> elaborderdetails { get; set; }
        public virtual employeemaster employeemaster { get; set; }
        public virtual patientmaster patientmaster { get; set; }
        public virtual refdoctor refdoctor { get; set; }
    }
}
