//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydb_finalEntities2 : DbContext
    {
        public mydb_finalEntities2()
            : base("name=mydb_finalEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categorymaster> categorymasters { get; set; }
        public DbSet<ebillorderdetail> ebillorderdetails { get; set; }
        public DbSet<ebillordermaster> ebillordermasters { get; set; }
        public DbSet<elaborderdetail> elaborderdetails { get; set; }
        public DbSet<elabordermaster> elabordermasters { get; set; }
        public DbSet<employeemaster> employeemasters { get; set; }
        public DbSet<labmaster> labmasters { get; set; }
        public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
        public DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
        public DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
        public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
        public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public DbSet<packagemaster> packagemasters { get; set; }
        public DbSet<patientlookup> patientlookups { get; set; }
        public DbSet<patientmaster> patientmasters { get; set; }
        public DbSet<profilemaster> profilemasters { get; set; }
        public DbSet<refdoctor> refdoctors { get; set; }
    }
}
