//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class profilemaster
    {
        public profilemaster()
        {
            this.labmasters = new HashSet<labmaster>();
        }
    
        public int profileid { get; set; }
        [Display(Name="Name")]
        [Required(ErrorMessage = "*")]
        public string profilename { get; set; }
        [Display(Name="Description")]
        [Required(ErrorMessage = "*")]
        public string profiledescription { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual ICollection<labmaster> labmasters { get; set; }
    }
}
