//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refdoctor
    {
        public refdoctor()
        {
            this.elabordermasters = new HashSet<elabordermaster>();
        }
    
        public int refdocid { get; set; }
        public string doctorname { get; set; }
        public string specialization { get; set; }
        public string refdoctorcol { get; set; }
    
        public virtual ICollection<elabordermaster> elabordermasters { get; set; }
    }
}
