//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebillorderdetail
    {
        public int ebillid { get; set; }
        public int labid { get; set; }
        public decimal amount { get; set; }
        public decimal quantity { get; set; }
        public int ebilldetailid { get; set; }
    
        public virtual ebillordermaster ebillordermaster { get; set; }
    }
}
