//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labmaster
    {
        public labmaster()
        {
            this.elaborderdetails = new HashSet<elaborderdetail>();
        }
    
        public int labid { get; set; }
        public string labname { get; set; }
        public string labdescription { get; set; }
        public Nullable<int> deleted { get; set; }
        public int profileid { get; set; }
        public int categoryid { get; set; }
        public Nullable<int> packageid { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual categorymaster categorymaster { get; set; }
        public virtual ICollection<elaborderdetail> elaborderdetails { get; set; }
        public virtual packagemaster packagemaster { get; set; }
        public virtual profilemaster profilemaster { get; set; }
    }
}
