//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagemaster
    {
        public packagemaster()
        {
            this.labmasters = new HashSet<labmaster>();
        }
    
        public int packageid { get; set; }
        public string packagename { get; set; }
        public string packagedescription { get; set; }
        public Nullable<int> deleted { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual ICollection<labmaster> labmasters { get; set; }
    }
}
