//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL_MVC_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientlookup
    {
        public int patientid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual patientmaster patientmaster { get; set; }
    }
}
